#!/bin/bash

# Set variables
KEY_NAME="school"
KEY_BITS=4096
PASSPHRASE="betty"

# Create the RSA key pair
ssh-keygen -t rsa -b $KEY_BITS -f $KEY_NAME -N "$PASSPHRASE"

# Output success message
if [ $? -eq 0 ]; then
    echo "RSA key pair '$KEY_NAME' created successfully."
else
    echo "Failed to create RSA key pair."
fi
